apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-web-app-ingress-fanout
  namespace: doit-lab-07
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    k8s-app: static-web-app-fanout
    k8s-scope: gke-ws-doit-lab-07
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          #
          # @info: This is our path to the v1 deployment
          # --
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: static-web-app-service-v1
                port:
                  number: 8080

          #
          # @info: This is our path to the v2 deployment
          # --
          - path: /v2/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: static-web-app-service-v2
                port:
                  number: 8080

          #
          # @info: This is our path to the v3 deployment
          # --
          - path: /v3/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: static-web-app-service-v3
                port:
                  number: 8080