apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-web-app-ingress
  namespace: doit-lab-06
  labels:
    k8s-app: static-web-app
    k8s-scope: gke-ws-doit-lab-06
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/load-balancer-name: my-static-web-app-lb
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: static-web-app-service
      port:
        number: 8080